### ISSUE TITLE
Assertion failure during training with ELMO

### ISSUE THREAD

**Issue by acDante** [hiroki13/span-based-srl#1]
Hey there! I came into some errors when trying to train your model on conll2012 dataset with ELMO embedding. I used this command"$ allennlp elmo ./data/conll2012.dev.txt ./data/elmo.conll2012.dev.hdf5 --all" to generate the required ELMO embedding files, but allenlp throws an error saying that the file cannot contain empty lines. Afterwards I delete all the empty lines between sentences to generate the ELMO embedding, and insert the empty lines again before running your model.

But I got some assertion failure during training as below: 
> Traceback (most recent call last):
  File "src/main.py", line 100, in <module>
    main()
  File "src/main.py", line 90, in main
    Trainer(argv=argv).train()
  File "/Users/xiaotang/Documents/SRL/span-based-srl/src/srl/trainers.py", line 100, in train
    vocab_label=vocab_label_train)
  File "/Users/xiaotang/Documents/SRL/span-based-srl/src/srl/preprocessors.py", line 126, in set_sent_params
    sent.set_elmo_emb(elmo_emb[str(index)])
  File "/Users/xiaotang/Documents/SRL/span-based-srl/src/utils/sent.py", line 70, in set_elmo_emb
    assert len(elmo_emb) == self.n_words
AssertionError

> Traceback (most recent call last):
  File "src/main.py", line 100, in <module>
    main()
  File "src/main.py", line 90, in main
    Trainer(argv=argv).train()
  File "/Users/xiaotang/Documents/SRL/span-based-srl/src/srl/trainers.py", line 100, in train
    vocab_label=vocab_label_train)
  File "/Users/xiaotang/Documents/SRL/span-based-srl/src/srl/preprocessors.py", line 129, in set_sent_params
    sent.set_span_triples_with_null(vocab_label.size())
  File "/Users/xiaotang/Documents/SRL/span-based-srl/src/utils/sent.py", line 146, in set_span_triples_with_null
    assert len(self.span_triples) == len(self.prd_indices)
AssertionError

What might be the possible reason behind this error ? How should I generate the ELMO embeddings in order to run your model ?

**Comment by acDante** [comment]
Besides, could you provide any pre-trianed models :-) ? I would like to evaluate the performance of your model on another dataset.
